spring.application.name=order-service


# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/order_service_db
spring.datasource.username=root
spring.datasource.password=Shubham@2904

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server
server.port=8081



# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.type.mapping=orderCreated:com.ecommerce.orderservice.kafka.OrderCreatedEvent
